### ISSUE TITLE
About the baseline model

### ISSUE THREAD

**Issue by ZihuaEvan** [232525/PureT#12]
Dear author:
Could you provide a training configs for the baseline model?
In the paper, Transformer without pre-fusion reaches 136.4 in CIDEr, and Transformer with pre-fusion reaches 137.5.
Thanks!

**Comment by 232525** [comment]
I am not sure if I can still find the relevant files. Actually, the GPU machine (for these experiments) got some error some time ago and I can not check the backup of this machine now because I am not in the lab recently.

**Comment by ZihuaEvan** [comment]
Thank you all the same.

**Comment by LeXueTao** [comment]
> Dear author: Could you provide a training configs for the baseline model? In the paper, Transformer without pre-fusion reaches 136.4 in CIDEr, and Transformer with pre-fusion reaches 137.5. Thanks!

Hello, have you successfully replicated the results of the Transformer model?，I train it with xe 0.49, scst 134. It's so mysterious.
