### ISSUE TITLE
PKL

### ISSUE THREAD

**Issue by yanjialele** [232525/PureT#2]
Hello!Thanks for your work!  What is the meaning of the coco_train_input.pkl and coco_train_target.pkl files under the ./mscoco/sent file? How is it generated?

**Comment by 232525** [comment]
For more details, you can refer to [image-captioning](https://github.com/JDAI-CV/image-captioning) and [self-critical.pytorch](https://github.com/ruotianluo/self-critical.pytorch). Actually coco_train_input.pkl and coco_train_output.pkl contain the groud truth captions (list of word indices) for training input and label. If you load and print the data, you can easily understand them.
