### ISSUE TITLE
some questions about PureT_SCST

### ISSUE THREAD

**Issue by zml110120** [232525/PureT#4]
Could you tell me which kind of GPU and how many you has uesd? I use V100-16GB and there is OOM error

**Comment by 232525** [comment]
V100-32GB, batch size of 10, single GPU is enough.

**Comment by 232525** [comment]
Actually 16G is enough, I try to train under SCST with batch size of 10, it just cost 5000M - 6000M CUDA memory.

**Comment by 232525** [comment]
> Actually 16G is enough, I try to train under SCST with batch size of 10, it just cost 5000M - 6000M CUDA memory.

Oh, I am sorry, it is wrong, I trained the model without the backbone model of SwinT, the full model may need more CUDA memory.
