### ISSUE TITLE
about performance gap between using backbone and not 

### ISSUE THREAD

**Issue by wanboyang** [232525/PureT#6]
Thanks for this amazing work and opening code。
I find a performance gap between using backbone and not in training, and the details are shown as follows:
![aa](https://user-images.githubusercontent.com/23290289/170403124-01880849-43a6-4201-bf03-da009b050e31.png)
the performance of using backbone and not being represented by PrueT_SCST and PrueT_SCST_ff, respectively.
Do  you find the same issue in your experiment?

**Comment by 232525** [comment]
I noticed this, but I did not do more experiments. So I am not sure why. However, based on my experience, the performance without backbone should be better than that shown in your tensorboard figure.

**Comment by wanboyang** [comment]
> I noticed this, but I did not do more experiments. So I am not sure why. However, based on my experience, the performance without backbone should be better than that shown in your tensorboard figure.

Thanks for replying. Could you provide the extracted swin feature used in this paper?
Thanks again.

**Comment by 232525** [comment]
> > I noticed this, but I did not do more experiments. So I am not sure why. However, based on my experience, the performance without backbone should be better than that shown in your tensorboard figure.
> 
> Thanks for replying. Could you provide the extracted swin feature used in this paper? Thanks again.

OK, I will upload them to 百度网盘, but it is almost 127GB, so need some time. I will reply to you when finished.

**Comment by wanboyang** [comment]
> > > I noticed this, but I did not do more experiments. So I am not sure why. However, based on my experience, the performance without backbone should be better than that shown in your tensorboard figure.
> > 
> > 
> > Thanks for replying. Could you provide the extracted swin feature used in this paper? Thanks again.
> 
> OK, I will upload them to 百度网盘, but it is almost 127GB, so need some time. I will reply to you when finished.

Thanks

**Comment by 232525** [comment]
I have uploaded the pre-extracted features to 百度网盘, you can find and download them from the [link](https://pan.baidu.com/s/1tyXGJx50sllS-zylN62ZAw)(提取码: hryh) listed in the README.

**Comment by wanboyang** [comment]
> I have uploaded the pre-extracted features to 百度网盘, you can find and download them from the [link](https://pan.baidu.com/s/1tyXGJx50sllS-zylN62ZAw)(提取码: hryh) listed in the README.

Thanks。 Do you choose the best cider score XE captioning model on val dataset for SCST initialization？

**Comment by 232525** [comment]
> > I have uploaded the pre-extracted features to 百度网盘, you can find and download them from the [link](https://pan.baidu.com/s/1tyXGJx50sllS-zylN62ZAw)(提取码: hryh) listed in the README.
> 
> Thanks。 Do you choose the best cider score XE captioning model on val dataset for SCST initialization？

Yes!

**Comment by wanboyang** [comment]
> > > I have uploaded the pre-extracted features to 百度网盘, you can find and download them from the [link](https://pan.baidu.com/s/1tyXGJx50sllS-zylN62ZAw)(提取码: hryh) listed in the README.
> > 
> > 
> > Thanks。 Do you choose the best cider score XE captioning model on val dataset for SCST initialization？
> 
> Yes!

Thanks

**Comment by wanboyang** [comment]
![捕获1](https://user-images.githubusercontent.com/23290289/174282434-a37f7706-7af9-429d-a5fa-7c0521f14ef7.PNG)
![捕获2](https://user-images.githubusercontent.com/23290289/174282452-898c5ab2-b6d2-4c5a-aaac-55a653dba9d8.PNG)
I use your swin features to train the pruet model, and the performance of this model is lower than reported in this paper too.
